### PR TITLE
Refactor

### LINKED ISSUE #22: CSS Lighthouse Audit and Screen Responsiveness

### PR DESCRIPTION
**Pull request by CaliHam**
What I did:
Went through code and changed small things everywhere. This PR will close #22 and #23 
Did this break anything?

- [x] No
- [ ]  Yes

Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x]  Bug fix (non-breaking change which fixes an issue)
- [x]  Refactor(DRY-ing up/ reorganizing code, etc.)
- [x]  Super small fix (Corrected a typo, removed a comment, etc.)
- [ ]  Skip all the other stuff and briefly explain the fix.

Checklist:

- [x]  If this code needs to be tested, all tests are passing
- [ ]  The code runs locally
- [ ]  There are comments where clarification/ organization is needed
- [x]  The code is DRY. If it's not, I tried my best
- [x]  I reviewed my code before pushing

### CODE REVIEW

**Review by hvohr — APPROVED** [review]
this looks great!!! thank you!

**Review by SethBurns — APPROVED** [review]

**Review by taranveersingh93 — CHANGES_REQUESTED** [review]
Hey! Clarifying questions: 
The "new-task-test" has a conflict I think. It's telling me "no tests found"
The 500 error test in "errorhandling_config" is failing for me. 

Do you see any of these at your end too?

**Comment by CaliHam** [comment]
> Hey! Clarifying questions: The "new-task-test" has a conflict I think. It's telling me "no tests found" The 500 error test in "errorhandling_config" is failing for me.
> 
> Do you see any of these at your end too?

Ahh there was a merge conflict I missed in the new-task file! Yeah the 500 is failing for me now too; what're we supposed to see when the server is down?

**Comment by CaliHam** [comment]
> > Hey! Clarifying questions: The "new-task-test" has a conflict I think. It's telling me "no tests found" The 500 error test in "errorhandling_config" is failing for me.
> > Do you see any of these at your end too?
> 
> Ahh there was a merge conflict I missed in the new-task file! Yeah the 500 is failing for me now too; what're we supposed to see when the server is down?

I made another error bear to render! All tests pass now!

**Review by taranveersingh93 — CHANGES_REQUESTED** [review]
In Error handling spec, could you please stub the get request for both savedtasks and tasks in all the describe blocks? Those network requests are going through for me.

**Review by taranveersingh93 — APPROVED** [review]
- Thorough tests
- Granular refactors of CSS that makes the app better visibly.
- Usage of liquid units for font size (sorry for missing that. thanks for correcting).
- Pleasant error messages and encompassing scenarios covered.
- Awareness about our data displayed by changing fixtures.
- Improved the function names and hence, increased code readability. 

I am super impressed by your code. Thank you for fencing the project with this PR. Highly appreciated!

**Pull request merged**
